# Pre-defined hand gesture templates
class Gesture:
    def __init__(self, label):
        self.gestures = {
            'One':          {'finger states':   [[2], [0], [3, 4], [3, 4], [3, 4]],
                             'direction':       'up',
                             'overlap':         None,
                             'boundary':        None},
            'Two':          {'finger states':   [[2], [0], [0], [3, 4], [3, 4]],
                             'direction':       'up',
                             'overlap':         None,
                             'boundary':        None},
            'Three':        {'finger states':   [[2], [0], [0], [0], [3, 4]],
                             'direction':       'up',
                             'overlap':         None,
                             'boundary':        None},
            'Four':         {'finger states':   [[2], [0], [0], [0], [0]],
                             'direction':       'up',
                             'overlap':         None,
                             'boundary':        None},
            'Five':         {'finger states':   [[0], [0], [0], [0], [0]],
                             'direction':       'up',
                             'overlap':         None,
                             'boundary':        None},
            'Six':          {'finger states':   [[0], [3, 4], [3, 4], [3, 4], [0]],
                             'direction':       'up',
                             'overlap':         None,
                             'boundary':        None},
            'Seven':        {'finger states':   [[1], [1], [1], [3, 4], [3, 4]],
                             'direction':       'up',
                             'overlap':         None,
                             'boundary':        None},
            'Eight':        {'finger states':   [[0], [0], [3, 4], [3, 4], [3, 4]],
                             'direction':       'up',
                             'overlap':         None,
                             'boundary':        None},
            'Nine':         {'finger states':   [[1, 2], [2], [3, 4], [3, 4], [3, 4]],
                             'direction':       'up',
                             'overlap':         None,
                             'boundary':        None},
            'Ten':          {'finger states':   [[2], [4], [4], [4], [4]],
                             'direction':       'up',
                             'overlap':         None,
                             'boundary':        None},
            'Claw':         {'finger states':   [[1], [1, 2], [1, 2], [1, 2], [1, 2]],
                             'direction':       'up',
                             'overlap':         None,
                             'boundary':        None},
            'Thumbs-up':    {'finger states':   [[0], [3, 4], [3, 4], [3, 4], [3, 4]],
                             'direction':       'left' if label == 'right' else 'right',
                             'overlap':         None,
                             'boundary':        {3: 4}},
            'Thumbs-down':  {'finger states':   [[0], [3, 4], [3, 4], [3, 4], [3, 4]],
                             'direction':       'left' if label == 'right' else 'right',
                             'overlap':         None,
                             'boundary':        {2: 4}},
            'Rock':         {'finger states':   [[2], [0], [3, 4], [3, 4], [0]],
                            'direction':       'up',
                            'overlap':         None,
                             'boundary':        None},
            'OK':           {'finger states':   [[1], [2], [0], [0], [0]],
                             'direction':       'up',
                             'overlap':         [[4, 8]],
                             'boundary':        None}
        }
        