class Gesture:
    def __init__(self, handedness):
        self.gestures = {
            'Yeah':         {'finger states':   [2, 0, 0, 2, 2],
                             'direction':       'up',
                             'boundary':        None},
            'OK':           {'finger states':   [2, 2, 0, 0, 0],
                             'direction':       'up',
                             'boundary':        None},
            'Thumbs-up':    {'finger states':   [0, 2, 2, 2, 2],
                             'direction':       'left' if handedness == 'Right' else 'right',
                             'boundary':        {3: 4}},
            'Thumbs-down':  {'finger states':   [0, 2, 2, 2, 2],
                             'direction':       'left' if handedness == 'Right' else 'right',
                             'boundary':        {2: 4}},
            'One':          {'finger states':   [2, 0, 2, 2, 2],
                             'direction':       'up',
                             'boundary':        None},
            'Three':        {'finger states':   [2, 0 ,0, 0, 2],
                             'direction':       'up',
                             'boundary':        None},
            'Four':         {'finger states':   [2, 0, 0, 0, 0],
                             'direction':       'up',
                             'boundary':        None},
            'Five':         {'finger states':   [0, 0, 0, 0, 0],
                             'direction':       'up',
                             'boundary':        None},
            'Fist':         {'finger states':   [2, 2, 2, 2, 2],
                             'direction':       'up',
                             'boundary':        None},
            'Six':          {'finger states':   [0, 2, 2, 2, 0],
                             'direction':       'up',
                             'boundary':        None},
            'Eight':        {'finger states':   [0, 0, 2, 2, 2],
                             'direction':       'up',
                             'boundary':        None},
            'Rock':         {'finger states':   [2, 0, 2, 2, 0],
                            'direction':       'up',
                             'boundary':        None}
        }
